version: '3.7'

volumes:
  postgres:

services:
  db:
    image: postgis/postgis
    container_name: raster-db
    env_file:
      - ./env/.development.env
    # This overwrites the POSTGRES_DB var in the env_file, as it should
    environment:
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/db:/docker-entrypoint-initdb.d
      - ./env:/initdb-env

  redis:
    container_name: "raster-redis"
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
